[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "5.2.4"
djangorestframework = "^3.16.0"
django-filter = "^25.1"

[tool.poetry.group.lint.dependencies]
black = "^25.1.0"
flake8 = "^7.3.0"
isort = "^6.0.1"


[tool.black]
line-length = 79

