# Generated by Django 5.2.4 on 2025-07-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="exchangeproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ожидает", "Ожидает"),
                    ("Принято", "Принято"),
                    ("Отклонено", "Отклонено"),
                ],
                default="Ожидает",
            ),
        ),
    ]
