# Generated by Django 5.2.4 on 2025-07-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("отклонено", "отклонено"),
                            ("ожидает", "принято"),
                            ("ожидает", "ожидает"),
                        ],
                        default="ожидает",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ad_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_receivers",
                        to="ads.ad",
                    ),
                ),
                (
                    "ad_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_senders",
                        to="ads.ad",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ad_sender", "ad_receiver"),
                        name="unique_sender_receiver",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ad_sender", models.F("ad_receiver")),
                            _negated=True,
                        ),
                        name="ad_sender_ne_ad_receiver",
                    ),
                ],
            },
        ),
    ]
